'use client'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/tw-sidebar'
import {useState} from 'react'
import type { NextPage } from 'next'
import { store } from './store'
import { Provider,Connect } from 'react-redux'
import { useAppSelector, useAppDispatch } from '../../app/app/hooks'
import ReactDOM from 'react-dom/client'
import React from 'react'


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'TESTING',
  description: 'Generated by create next app',
  name: 'viewport',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
  //const theme = useAppSelector((state) => state.theme.value)
 
  //const theme = "dark";
 
  return (
    <Provider store={store}>
        <html className="h-full bg-white">
          <body className="h-full">
          <div>
            <Sidebar /> 
              {children}
          </div> 
          </body>
       </html>
       </Provider>
  )
}
