import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react";
import { AppProps } from "next/app";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TESTING',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
